USE tddag1;

DROP TABLE IF EXISTS CarparkLot;
DROP TABLE IF EXISTS LotType;
DROP TABLE IF EXISTS SeasonalPass;
DROP TABLE IF EXISTS Offence;
DROP TABLE IF EXISTS ParkingSession;
DROP TABLE IF EXISTS Vehicle;
DROP TABLE IF EXISTS Person;
DROP TABLE IF EXISTS Residence;
DROP TABLE IF EXISTS HDBBlock;
DROP TABLE IF EXISTS VehicleModel;
DROP TABLE IF EXISTS ShortTermRates;
DROP TABLE IF EXISTS ParkingRule;
DROP TABLE IF EXISTS SeasonRate;
DROP TABLE IF EXISTS MSCP;
DROP TABLE IF EXISTS Carpark;